from __future__ import annotations

# PRD v2.3 standard reason codes plus runtime-specific fail-closed extensions.
UNAVAILABLE_REASONS = {
    "NO_MODEL_BEATS_BASELINE",
    "INSUFFICIENT_DATA",
    "INSUFFICIENT_EFFECTIVE_SAMPLE",
    "CALIBRATION_FAILED",
    "DATA_HEALTH_CRITICAL",
    "MODEL_DEGRADED",
    "MODEL_ARTIFACT_MISSING",
    "FEATURE_UNAVAILABLE",
    "SOURCE_CONTRACT_FAILED",
    "SHADOW_INSUFFICIENT",
    "REGISTRY_INCOMPLETE",
    "LEAKAGE_DETECTED",
    "TRAIN_SERVE_SKEW",
    "HOLDOUT_CONTAMINATED",
    "NO_PRODUCTION_APPROVAL",
    "MODEL_VERSION_MISMATCH",
    "MODEL_ARTIFACT_MISMATCH",
    "MODEL_UNRELIABLE",
    "STALE_DATA",
    "EMERGENCY_FREEZE",
    "PUBLICATION_DISABLED",
    "NO_SHADOW_CANDIDATE",
    "NO_PRODUCTION_MODEL",
}

INVALID_REASONS = {"LEAKAGE_DETECTED", "HOLDOUT_CONTAMINATED", "TRAIN_SERVE_SKEW"}


def validate_reason_code(reason: str | None) -> bool:
    return bool(reason and reason in UNAVAILABLE_REASONS)
